apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ template "health_exporter.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: '{{ template "health_exporter.fullname" . }}'
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: '{{ template "health_exporter.fullname" . }}'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: '{{ template "health_exporter.fullname" . }}'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - '{{ template "health_exporter.fullname" . }}'
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: health-exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        volumeMounts:
        - mountPath: /app/config.yaml
          name: config
          subPath: config.yaml
        imagePullPolicy: Always
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: '{{ .Values.config.listen }}'
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: '{{ .Values.config.listen }}'
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: '{{ .Values.config.listen }}'
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: '{{ template "health_exporter.fullname" . }}'
            items:
            - key: config.yaml
              path: config.yaml
