apiVersion: v1
kind: Service
metadata:
  name: '{{ template "health_exporter.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: '{{ .Values.config.listen }}'
  selector:
    app: '{{ template "health_exporter.fullname" . }}'
